### ISSUE TITLE
filter or mark locked and closed accounts.

### ISSUE THREAD

**Issue by persuader** [iomarmochtar/zmbr_weakpwd_scanner#1]
Can i filter or mark accounts that are locked or closed ? Got any tips?

**Comment by iomarmochtar** [comment]
Did you mean by exclude scanning for account with status closed ?

**Comment by persuader** [comment]
Yes.

**Comment by iomarmochtar** [comment]
use this ldap filter for argument -f 

-f "(&(objectClass=zimbraAccount)(!(zimbraIsSystemAccount=TRUE))(!(zimbraIsSystemResource=TRUE))(!(zimbraMailStatus=disabled)))"

**Comment by persuader** [comment]
10x works like a charm . If your shell is bash it must be enclosed in ' instead of ".
